# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d625d4ca1ab56bc918f023e196a5cec7415bca3acf958e2aef2abad70abcbf3f1e21d49f134dccba1ad1411a2d7bde6eca081f552666782336063e3dd81c0397

test:
  secret_key_base: 8940e00ce051102d88cf966c9dc8ff88976dc9cfb128b5cbe8293e2c5b4db20f19ada1e72e40fcb7b266c7e1185c30d5684c7b26307d308ce8df208897a9f7be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
